version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: smartdoc-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartdoc
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpass
    ports:
      - "3306:3306"
    volumes:
      - smartdoc-db-data:/var/lib/mysql
    networks:
      - smartdoc-network


  adminer:
    image: adminer
    container_name: smartdoc-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - smartdoc-network


volumes:
  smartdoc-db-data:
  smartdoc-app-data:

networks:
  smartdoc-network:
    driver: bridge